### ISSUE TITLE
New articles need to be added

### ISSUE THREAD

**Issue by victor-infosec** [MichaelKoczwara/Awesome-CobaltStrike-Defence#10]
Cobalt Strike Hunting — simple PCAP and Beacon Analysis
https://michaelkoczwara.medium.com/cobalt-strike-hunting-simple-pcap-and-beacon-analysis-f51c36ce6811

Guide to Named Pipes and Hunting for Cobalt Strike Pipes
https://svch0st.medium.com/guide-to-named-pipes-and-hunting-for-cobalt-strike-pipes-dc46b2c5f575

**Comment by MichaelKoczwara** [comment]
Thanks!
