### ISSUE TITLE
Data: Mining data from Cobalt Strike beacons

### ISSUE THREAD

**Issue by ssnkhan** [MichaelKoczwara/Awesome-CobaltStrike-Defence#30]
NCC have published their collections of Cobalt Strike beacons spanning 2018-2022:

> The published dataset contains historical beacon metadata ranging from 2018 to 2022. The dataset `beacons.jsonl.gz` is a GZIP compressed file containing 128,340 rows of beacon metadata as JSON-lines.

**Report**
https://research.nccgroup.com/2022/03/25/mining-data-from-cobalt-strike-beacons/

**Data**
https://github.com/fox-it/cobaltstrike-beacon-data

**Comment by MichaelKoczwara** [comment]
Cheers!
